# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqtsfplotter_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 960)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 960))
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("stop-sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_left = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_left.sizePolicy().hasHeightForWidth())
        self.widget_left.setSizePolicy(sizePolicy)
        self.widget_left.setMinimumSize(QtCore.QSize(384, 0))
        self.widget_left.setObjectName("widget_left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_left)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_Data = QtWidgets.QLabel(self.widget_left)
        self.label_Data.setObjectName("label_Data")
        self.horizontalLayout_9.addWidget(self.label_Data)
        self.pushButton_Import_Raw_Data = QtWidgets.QPushButton(self.widget_left)
        icon = QtGui.QIcon.fromTheme("x-office-spreadsheet")
        self.pushButton_Import_Raw_Data.setIcon(icon)
        self.pushButton_Import_Raw_Data.setObjectName("pushButton_Import_Raw_Data")
        self.horizontalLayout_9.addWidget(self.pushButton_Import_Raw_Data)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.tabWidget_Data = QtWidgets.QTabWidget(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tabWidget_Data.sizePolicy().hasHeightForWidth())
        self.tabWidget_Data.setSizePolicy(sizePolicy)
        self.tabWidget_Data.setObjectName("tabWidget_Data")
        self.tab_Raw_Data = QtWidgets.QWidget()
        self.tab_Raw_Data.setObjectName("tab_Raw_Data")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_Raw_Data)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.comboBox_Select_File = QtWidgets.QComboBox(self.tab_Raw_Data)
        self.comboBox_Select_File.setObjectName("comboBox_Select_File")
        self.horizontalLayout_10.addWidget(self.comboBox_Select_File)
        self.toolButton_Remove_File = QtWidgets.QToolButton(self.tab_Raw_Data)
        icon = QtGui.QIcon.fromTheme("remove")
        self.toolButton_Remove_File.setIcon(icon)
        self.toolButton_Remove_File.setObjectName("toolButton_Remove_File")
        self.horizontalLayout_10.addWidget(self.toolButton_Remove_File)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Current_Axis = QtWidgets.QLabel(self.tab_Raw_Data)
        self.label_Current_Axis.setObjectName("label_Current_Axis")
        self.horizontalLayout_3.addWidget(self.label_Current_Axis)
        self.toolButton_Toggle_Axis = QtWidgets.QToolButton(self.tab_Raw_Data)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.toolButton_Toggle_Axis.setFont(font)
        self.toolButton_Toggle_Axis.setObjectName("toolButton_Toggle_Axis")
        self.horizontalLayout_3.addWidget(self.toolButton_Toggle_Axis)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.listView_Raw_Traces = QtWidgets.QListView(self.tab_Raw_Data)
        self.listView_Raw_Traces.setAlternatingRowColors(True)
        self.listView_Raw_Traces.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listView_Raw_Traces.setObjectName("listView_Raw_Traces")
        self.verticalLayout_2.addWidget(self.listView_Raw_Traces)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.toolButton_Range_Select_Linear = QtWidgets.QToolButton(self.tab_Raw_Data)
        self.toolButton_Range_Select_Linear.setObjectName("toolButton_Range_Select_Linear")
        self.horizontalLayout_12.addWidget(self.toolButton_Range_Select_Linear)
        self.toolButton_Range_Select_Log = QtWidgets.QToolButton(self.tab_Raw_Data)
        self.toolButton_Range_Select_Log.setObjectName("toolButton_Range_Select_Log")
        self.horizontalLayout_12.addWidget(self.toolButton_Range_Select_Log)
        self.doubleSpinBox_Range_From = QtWidgets.QDoubleSpinBox(self.tab_Raw_Data)
        self.doubleSpinBox_Range_From.setDecimals(3)
        self.doubleSpinBox_Range_From.setMaximum(1000000.0)
        self.doubleSpinBox_Range_From.setObjectName("doubleSpinBox_Range_From")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_Range_From)
        self.label_11 = QtWidgets.QLabel(self.tab_Raw_Data)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.doubleSpinBox_Range_To = QtWidgets.QDoubleSpinBox(self.tab_Raw_Data)
        self.doubleSpinBox_Range_To.setDecimals(3)
        self.doubleSpinBox_Range_To.setMaximum(1000000.0)
        self.doubleSpinBox_Range_To.setObjectName("doubleSpinBox_Range_To")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_Range_To)
        self.label_12 = QtWidgets.QLabel(self.tab_Raw_Data)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.spinBox_Range_Steps = QtWidgets.QSpinBox(self.tab_Raw_Data)
        self.spinBox_Range_Steps.setMinimum(2)
        self.spinBox_Range_Steps.setMaximum(1000)
        self.spinBox_Range_Steps.setObjectName("spinBox_Range_Steps")
        self.horizontalLayout_12.addWidget(self.spinBox_Range_Steps)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton_All_Wavelengths = QtWidgets.QToolButton(self.tab_Raw_Data)
        icon = QtGui.QIcon.fromTheme("edit-select-all")
        self.toolButton_All_Wavelengths.setIcon(icon)
        self.toolButton_All_Wavelengths.setObjectName("toolButton_All_Wavelengths")
        self.horizontalLayout_4.addWidget(self.toolButton_All_Wavelengths)
        self.toolButton_None_Wavelengths = QtWidgets.QToolButton(self.tab_Raw_Data)
        icon = QtGui.QIcon.fromTheme("edit-clear")
        self.toolButton_None_Wavelengths.setIcon(icon)
        self.toolButton_None_Wavelengths.setObjectName("toolButton_None_Wavelengths")
        self.horizontalLayout_4.addWidget(self.toolButton_None_Wavelengths)
        self.toolButton_Add_This_File = QtWidgets.QToolButton(self.tab_Raw_Data)
        icon = QtGui.QIcon.fromTheme("go-down")
        self.toolButton_Add_This_File.setIcon(icon)
        self.toolButton_Add_This_File.setObjectName("toolButton_Add_This_File")
        self.horizontalLayout_4.addWidget(self.toolButton_Add_This_File)
        self.toolButton_Add_All_Files = QtWidgets.QToolButton(self.tab_Raw_Data)
        icon = QtGui.QIcon.fromTheme("edit-copy")
        self.toolButton_Add_All_Files.setIcon(icon)
        self.toolButton_Add_All_Files.setObjectName("toolButton_Add_All_Files")
        self.horizontalLayout_4.addWidget(self.toolButton_Add_All_Files)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.toolButton_SVD = QtWidgets.QToolButton(self.tab_Raw_Data)
        self.toolButton_SVD.setObjectName("toolButton_SVD")
        self.horizontalLayout_4.addWidget(self.toolButton_SVD)
        self.spinBox_SVD = QtWidgets.QSpinBox(self.tab_Raw_Data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_SVD.sizePolicy().hasHeightForWidth())
        self.spinBox_SVD.setSizePolicy(sizePolicy)
        self.spinBox_SVD.setMinimum(1)
        self.spinBox_SVD.setMaximum(100)
        self.spinBox_SVD.setProperty("value", 5)
        self.spinBox_SVD.setObjectName("spinBox_SVD")
        self.horizontalLayout_4.addWidget(self.spinBox_SVD)
        self.checkBox_eigvalue = QtWidgets.QCheckBox(self.tab_Raw_Data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_eigvalue.sizePolicy().hasHeightForWidth())
        self.checkBox_eigvalue.setSizePolicy(sizePolicy)
        self.checkBox_eigvalue.setObjectName("checkBox_eigvalue")
        self.horizontalLayout_4.addWidget(self.checkBox_eigvalue)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.tabWidget_Data.addTab(self.tab_Raw_Data, "")
        self.verticalLayout.addWidget(self.tabWidget_Data)
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.label_7 = QtWidgets.QLabel(self.widget_left)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_1.addWidget(self.label_7)
        self.label_dpiNumber = QtWidgets.QLabel(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dpiNumber.sizePolicy().hasHeightForWidth())
        self.label_dpiNumber.setSizePolicy(sizePolicy)
        self.label_dpiNumber.setObjectName("label_dpiNumber")
        self.horizontalLayout_1.addWidget(self.label_dpiNumber)
        self.label_dpi = QtWidgets.QLabel(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dpi.sizePolicy().hasHeightForWidth())
        self.label_dpi.setSizePolicy(sizePolicy)
        self.label_dpi.setObjectName("label_dpi")
        self.horizontalLayout_1.addWidget(self.label_dpi)
        self.horizontalSlider_DPI = QtWidgets.QSlider(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_DPI.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_DPI.setSizePolicy(sizePolicy)
        self.horizontalSlider_DPI.setMinimum(100)
        self.horizontalSlider_DPI.setMaximum(900)
        self.horizontalSlider_DPI.setSingleStep(50)
        self.horizontalSlider_DPI.setPageStep(100)
        self.horizontalSlider_DPI.setProperty("value", 300)
        self.horizontalSlider_DPI.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_DPI.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_DPI.setTickInterval(150)
        self.horizontalSlider_DPI.setObjectName("horizontalSlider_DPI")
        self.horizontalLayout_1.addWidget(self.horizontalSlider_DPI)
        self.pushButton_Save_Figure = QtWidgets.QPushButton(self.widget_left)
        icon = QtGui.QIcon.fromTheme("image-x-generic")
        self.pushButton_Save_Figure.setIcon(icon)
        self.pushButton_Save_Figure.setObjectName("pushButton_Save_Figure")
        self.horizontalLayout_1.addWidget(self.pushButton_Save_Figure)
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        self.tabWidget = QtWidgets.QTabWidget(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Time_Traces = QtWidgets.QWidget()
        self.tab_Time_Traces.setObjectName("tab_Time_Traces")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_Time_Traces)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableView_Traces = QtWidgets.QTableView(self.tab_Time_Traces)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tableView_Traces.sizePolicy().hasHeightForWidth())
        self.tableView_Traces.setSizePolicy(sizePolicy)
        self.tableView_Traces.setAlternatingRowColors(True)
        self.tableView_Traces.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableView_Traces.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_Traces.setObjectName("tableView_Traces")
        self.tableView_Traces.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView_Traces.horizontalHeader().setDefaultSectionSize(120)
        self.tableView_Traces.horizontalHeader().setHighlightSections(False)
        self.tableView_Traces.horizontalHeader().setMinimumSectionSize(20)
        self.tableView_Traces.horizontalHeader().setStretchLastSection(True)
        self.tableView_Traces.verticalHeader().setVisible(False)
        self.verticalLayout_6.addWidget(self.tableView_Traces)
        self.tabWidget.addTab(self.tab_Time_Traces, "")
        self.tab_Spectra = QtWidgets.QWidget()
        self.tab_Spectra.setObjectName("tab_Spectra")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_Spectra)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableView_Spectra = QtWidgets.QTableView(self.tab_Spectra)
        self.tableView_Spectra.setAlternatingRowColors(True)
        self.tableView_Spectra.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableView_Spectra.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_Spectra.setObjectName("tableView_Spectra")
        self.tableView_Spectra.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView_Spectra.horizontalHeader().setDefaultSectionSize(120)
        self.tableView_Spectra.horizontalHeader().setHighlightSections(False)
        self.tableView_Spectra.horizontalHeader().setMinimumSectionSize(20)
        self.tableView_Spectra.horizontalHeader().setStretchLastSection(True)
        self.tableView_Spectra.verticalHeader().setVisible(False)
        self.verticalLayout_7.addWidget(self.tableView_Spectra)
        self.tabWidget.addTab(self.tab_Spectra, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toolButton_All_Traces = QtWidgets.QToolButton(self.widget_left)
        icon = QtGui.QIcon.fromTheme("edit-select-all")
        self.toolButton_All_Traces.setIcon(icon)
        self.toolButton_All_Traces.setObjectName("toolButton_All_Traces")
        self.horizontalLayout_6.addWidget(self.toolButton_All_Traces)
        self.toolButton_None_Traces = QtWidgets.QToolButton(self.widget_left)
        icon = QtGui.QIcon.fromTheme("edit-clear")
        self.toolButton_None_Traces.setIcon(icon)
        self.toolButton_None_Traces.setObjectName("toolButton_None_Traces")
        self.horizontalLayout_6.addWidget(self.toolButton_None_Traces)
        self.toolButton_Remove_Selected_Traces = QtWidgets.QToolButton(self.widget_left)
        icon = QtGui.QIcon.fromTheme("edit-delete")
        self.toolButton_Remove_Selected_Traces.setIcon(icon)
        self.toolButton_Remove_Selected_Traces.setObjectName("toolButton_Remove_Selected_Traces")
        self.horizontalLayout_6.addWidget(self.toolButton_Remove_Selected_Traces)
        self.toolButton_Line = QtWidgets.QToolButton(self.widget_left)
        self.toolButton_Line.setObjectName("toolButton_Line")
        self.horizontalLayout_6.addWidget(self.toolButton_Line)
        self.toolButton_Scatter = QtWidgets.QToolButton(self.widget_left)
        self.toolButton_Scatter.setObjectName("toolButton_Scatter")
        self.horizontalLayout_6.addWidget(self.toolButton_Scatter)
        self.toolButton_Hide = QtWidgets.QToolButton(self.widget_left)
        self.toolButton_Hide.setObjectName("toolButton_Hide")
        self.horizontalLayout_6.addWidget(self.toolButton_Hide)
        self.pushButton_Export_Traces = QtWidgets.QPushButton(self.widget_left)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.pushButton_Export_Traces.setIcon(icon)
        self.pushButton_Export_Traces.setObjectName("pushButton_Export_Traces")
        self.horizontalLayout_6.addWidget(self.pushButton_Export_Traces)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButton_Add_By = QtWidgets.QToolButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_Add_By.sizePolicy().hasHeightForWidth())
        self.toolButton_Add_By.setSizePolicy(sizePolicy)
        self.toolButton_Add_By.setObjectName("toolButton_Add_By")
        self.horizontalLayout_2.addWidget(self.toolButton_Add_By)
        self.toolButton_Mul_By = QtWidgets.QToolButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_Mul_By.sizePolicy().hasHeightForWidth())
        self.toolButton_Mul_By.setSizePolicy(sizePolicy)
        self.toolButton_Mul_By.setObjectName("toolButton_Mul_By")
        self.horizontalLayout_2.addWidget(self.toolButton_Mul_By)
        self.label_6 = QtWidgets.QLabel(self.widget_left)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.doubleSpinBox_By = QtWidgets.QDoubleSpinBox(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_By.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_By.setSizePolicy(sizePolicy)
        self.doubleSpinBox_By.setToolTip("")
        self.doubleSpinBox_By.setDecimals(3)
        self.doubleSpinBox_By.setMinimum(-100.0)
        self.doubleSpinBox_By.setMaximum(100.0)
        self.doubleSpinBox_By.setSingleStep(0.01)
        self.doubleSpinBox_By.setObjectName("doubleSpinBox_By")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_By, 0, QtCore.Qt.AlignHCenter)
        self.toolButton_Internal_Ref = QtWidgets.QToolButton(self.widget_left)
        self.toolButton_Internal_Ref.setObjectName("toolButton_Internal_Ref")
        self.horizontalLayout_2.addWidget(self.toolButton_Internal_Ref)
        self.label_8 = QtWidgets.QLabel(self.widget_left)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.doubleSpinBox_Internal_Ref = QtWidgets.QDoubleSpinBox(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_Internal_Ref.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_Internal_Ref.setSizePolicy(sizePolicy)
        self.doubleSpinBox_Internal_Ref.setDecimals(3)
        self.doubleSpinBox_Internal_Ref.setMaximum(1000000.0)
        self.doubleSpinBox_Internal_Ref.setObjectName("doubleSpinBox_Internal_Ref")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_Internal_Ref)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.toolButton_Ref_To = QtWidgets.QToolButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_Ref_To.sizePolicy().hasHeightForWidth())
        self.toolButton_Ref_To.setSizePolicy(sizePolicy)
        self.toolButton_Ref_To.setObjectName("toolButton_Ref_To")
        self.horizontalLayout_7.addWidget(self.toolButton_Ref_To)
        self.label_9 = QtWidgets.QLabel(self.widget_left)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.comboBox_Ref_To = QtWidgets.QComboBox(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Ref_To.sizePolicy().hasHeightForWidth())
        self.comboBox_Ref_To.setSizePolicy(sizePolicy)
        self.comboBox_Ref_To.setObjectName("comboBox_Ref_To")
        self.horizontalLayout_7.addWidget(self.comboBox_Ref_To)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_Exec_Command = QtWidgets.QLineEdit(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Exec_Command.sizePolicy().hasHeightForWidth())
        self.lineEdit_Exec_Command.setSizePolicy(sizePolicy)
        self.lineEdit_Exec_Command.setObjectName("lineEdit_Exec_Command")
        self.horizontalLayout_5.addWidget(self.lineEdit_Exec_Command)
        self.pushButton_Exec = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Exec.sizePolicy().hasHeightForWidth())
        self.pushButton_Exec.setSizePolicy(sizePolicy)
        self.pushButton_Exec.setObjectName("pushButton_Exec")
        self.horizontalLayout_5.addWidget(self.pushButton_Exec)
        self.toolButton_Reset = QtWidgets.QToolButton(self.widget_left)
        self.toolButton_Reset.setObjectName("toolButton_Reset")
        self.horizontalLayout_5.addWidget(self.toolButton_Reset)
        self.pushButton_About = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_About.sizePolicy().hasHeightForWidth())
        self.pushButton_About.setSizePolicy(sizePolicy)
        self.pushButton_About.setObjectName("pushButton_About")
        self.horizontalLayout_5.addWidget(self.pushButton_About)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addWidget(self.widget_left)
        self.widget_right = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_right.sizePolicy().hasHeightForWidth())
        self.widget_right.setSizePolicy(sizePolicy)
        self.widget_right.setMinimumSize(QtCore.QSize(600, 600))
        self.widget_right.setObjectName("widget_right")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_right)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.stackedWidget_right = QtWidgets.QStackedWidget(self.widget_right)
        self.stackedWidget_right.setMinimumSize(QtCore.QSize(600, 0))
        self.stackedWidget_right.setObjectName("stackedWidget_right")
        self.stackedWidget_Traces_Plot = QtWidgets.QWidget()
        self.stackedWidget_Traces_Plot.setObjectName("stackedWidget_Traces_Plot")
        self.verticalLayout_Traces_Plot = QtWidgets.QVBoxLayout(self.stackedWidget_Traces_Plot)
        self.verticalLayout_Traces_Plot.setObjectName("verticalLayout_Traces_Plot")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_Traces_Plot.addLayout(self.verticalLayout_4)
        self.stackedWidget_right.addWidget(self.stackedWidget_Traces_Plot)
        self.stackedWidget_Spectra_Plot = QtWidgets.QWidget()
        self.stackedWidget_Spectra_Plot.setObjectName("stackedWidget_Spectra_Plot")
        self.verticalLayout_Spectra_Plot = QtWidgets.QVBoxLayout(self.stackedWidget_Spectra_Plot)
        self.verticalLayout_Spectra_Plot.setObjectName("verticalLayout_Spectra_Plot")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_Spectra_Plot.addLayout(self.verticalLayout_5)
        self.stackedWidget_right.addWidget(self.stackedWidget_Spectra_Plot)
        self.verticalLayout_9.addWidget(self.stackedWidget_right)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_xRange = QtWidgets.QLabel(self.widget_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_xRange.sizePolicy().hasHeightForWidth())
        self.label_xRange.setSizePolicy(sizePolicy)
        self.label_xRange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_xRange.setObjectName("label_xRange")
        self.horizontalLayout_11.addWidget(self.label_xRange)
        self.doubleSpinBox_xMin = QtWidgets.QDoubleSpinBox(self.widget_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_xMin.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_xMin.setSizePolicy(sizePolicy)
        self.doubleSpinBox_xMin.setDecimals(3)
        self.doubleSpinBox_xMin.setMinimum(-1000.0)
        self.doubleSpinBox_xMin.setMaximum(1000.0)
        self.doubleSpinBox_xMin.setObjectName("doubleSpinBox_xMin")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_xMin)
        self.doubleSpinBox_xMax = QtWidgets.QDoubleSpinBox(self.widget_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_xMax.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_xMax.setSizePolicy(sizePolicy)
        self.doubleSpinBox_xMax.setDecimals(3)
        self.doubleSpinBox_xMax.setMinimum(-1000.0)
        self.doubleSpinBox_xMax.setMaximum(1000.0)
        self.doubleSpinBox_xMax.setObjectName("doubleSpinBox_xMax")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_xMax)
        self.checkBox_LogX = QtWidgets.QCheckBox(self.widget_right)
        self.checkBox_LogX.setObjectName("checkBox_LogX")
        self.horizontalLayout_11.addWidget(self.checkBox_LogX)
        self.label_yRange = QtWidgets.QLabel(self.widget_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_yRange.sizePolicy().hasHeightForWidth())
        self.label_yRange.setSizePolicy(sizePolicy)
        self.label_yRange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_yRange.setObjectName("label_yRange")
        self.horizontalLayout_11.addWidget(self.label_yRange)
        self.doubleSpinBox_yMin = QtWidgets.QDoubleSpinBox(self.widget_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_yMin.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_yMin.setSizePolicy(sizePolicy)
        self.doubleSpinBox_yMin.setDecimals(3)
        self.doubleSpinBox_yMin.setMinimum(-3.0)
        self.doubleSpinBox_yMin.setMaximum(3.0)
        self.doubleSpinBox_yMin.setSingleStep(0.05)
        self.doubleSpinBox_yMin.setObjectName("doubleSpinBox_yMin")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_yMin)
        self.doubleSpinBox_yMax = QtWidgets.QDoubleSpinBox(self.widget_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_yMax.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_yMax.setSizePolicy(sizePolicy)
        self.doubleSpinBox_yMax.setDecimals(3)
        self.doubleSpinBox_yMax.setMinimum(-3.0)
        self.doubleSpinBox_yMax.setMaximum(3.0)
        self.doubleSpinBox_yMax.setSingleStep(0.05)
        self.doubleSpinBox_yMax.setObjectName("doubleSpinBox_yMax")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_yMax)
        self.checkBox_LogY = QtWidgets.QCheckBox(self.widget_right)
        self.checkBox_LogY.setObjectName("checkBox_LogY")
        self.horizontalLayout_11.addWidget(self.checkBox_LogY)
        self.toolButton_Apply_Range = QtWidgets.QToolButton(self.widget_right)
        self.toolButton_Apply_Range.setObjectName("toolButton_Apply_Range")
        self.horizontalLayout_11.addWidget(self.toolButton_Apply_Range)
        self.toolButton_Auto_Range = QtWidgets.QToolButton(self.widget_right)
        self.toolButton_Auto_Range.setObjectName("toolButton_Auto_Range")
        self.horizontalLayout_11.addWidget(self.toolButton_Auto_Range)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_Grid = QtWidgets.QCheckBox(self.widget_right)
        self.checkBox_Grid.setObjectName("checkBox_Grid")
        self.horizontalLayout_8.addWidget(self.checkBox_Grid)
        self.checkBox_Legend = QtWidgets.QCheckBox(self.widget_right)
        self.checkBox_Legend.setObjectName("checkBox_Legend")
        self.horizontalLayout_8.addWidget(self.checkBox_Legend)
        self.label_3 = QtWidgets.QLabel(self.widget_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.spinBox_Font_Size = QtWidgets.QSpinBox(self.widget_right)
        self.spinBox_Font_Size.setSuffix("")
        self.spinBox_Font_Size.setMinimum(8)
        self.spinBox_Font_Size.setMaximum(100)
        self.spinBox_Font_Size.setSingleStep(4)
        self.spinBox_Font_Size.setProperty("value", 16)
        self.spinBox_Font_Size.setObjectName("spinBox_Font_Size")
        self.horizontalLayout_8.addWidget(self.spinBox_Font_Size)
        self.label_4 = QtWidgets.QLabel(self.widget_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.doubleSpinBox_Line_Width = QtWidgets.QDoubleSpinBox(self.widget_right)
        self.doubleSpinBox_Line_Width.setSuffix("")
        self.doubleSpinBox_Line_Width.setDecimals(1)
        self.doubleSpinBox_Line_Width.setMinimum(0.5)
        self.doubleSpinBox_Line_Width.setMaximum(16.0)
        self.doubleSpinBox_Line_Width.setSingleStep(0.5)
        self.doubleSpinBox_Line_Width.setProperty("value", 3.0)
        self.doubleSpinBox_Line_Width.setObjectName("doubleSpinBox_Line_Width")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_Line_Width)
        self.label_2 = QtWidgets.QLabel(self.widget_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.doubleSpinBox_Marker_Size = QtWidgets.QDoubleSpinBox(self.widget_right)
        self.doubleSpinBox_Marker_Size.setDecimals(1)
        self.doubleSpinBox_Marker_Size.setMinimum(0.5)
        self.doubleSpinBox_Marker_Size.setMaximum(20.0)
        self.doubleSpinBox_Marker_Size.setSingleStep(0.5)
        self.doubleSpinBox_Marker_Size.setProperty("value", 2.0)
        self.doubleSpinBox_Marker_Size.setObjectName("doubleSpinBox_Marker_Size")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_Marker_Size)
        self.label = QtWidgets.QLabel(self.widget_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.spinBox_Markevery = QtWidgets.QSpinBox(self.widget_right)
        self.spinBox_Markevery.setMinimum(20)
        self.spinBox_Markevery.setMaximum(1000)
        self.spinBox_Markevery.setSingleStep(20)
        self.spinBox_Markevery.setProperty("value", 60)
        self.spinBox_Markevery.setObjectName("spinBox_Markevery")
        self.horizontalLayout_8.addWidget(self.spinBox_Markevery)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout.addWidget(self.widget_right)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget_Data.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.horizontalSlider_DPI.valueChanged['int'].connect(self.label_dpiNumber.setNum)
        self.toolButton_All_Wavelengths.clicked.connect(self.listView_Raw_Traces.selectAll)
        self.toolButton_None_Wavelengths.clicked.connect(self.listView_Raw_Traces.clearSelection)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyQt Stopped-Flow Plotter"))
        self.label_Data.setText(_translate("MainWindow", "Data"))
        self.pushButton_Import_Raw_Data.setToolTip(_translate("MainWindow", "Import raw data from file(s)."))
        self.pushButton_Import_Raw_Data.setText(_translate("MainWindow", "Import Raw Data ..."))
        self.comboBox_Select_File.setToolTip(_translate("MainWindow", "Select a file to see the data inside."))
        self.toolButton_Remove_File.setToolTip(_translate("MainWindow", "Remove current file from list."))
        self.toolButton_Remove_File.setText(_translate("MainWindow", "Remove"))
        self.label_Current_Axis.setToolTip(_translate("MainWindow", "Time traces at different wavelengths."))
        self.label_Current_Axis.setText(_translate("MainWindow", "Selection Axis: Wavelengths"))
        self.toolButton_Toggle_Axis.setToolTip(_translate("MainWindow", "Toggle between time and wavelength axes."))
        self.toolButton_Toggle_Axis.setText(_translate("MainWindow", "Toggle"))
        self.toolButton_Range_Select_Linear.setToolTip(_translate("MainWindow", "Select traces above in linear intervals."))
        self.toolButton_Range_Select_Linear.setText(_translate("MainWindow", "Linear"))
        self.toolButton_Range_Select_Log.setToolTip(_translate("MainWindow", "Select traces above in logarithmic intervals."))
        self.toolButton_Range_Select_Log.setText(_translate("MainWindow", "Log"))
        self.doubleSpinBox_Range_From.setToolTip(_translate("MainWindow", "Lower limit of range."))
        self.doubleSpinBox_Range_From.setSuffix(_translate("MainWindow", " nm"))
        self.label_11.setText(_translate("MainWindow", "To"))
        self.doubleSpinBox_Range_To.setToolTip(_translate("MainWindow", "Upper limit of range."))
        self.doubleSpinBox_Range_To.setSuffix(_translate("MainWindow", " nm"))
        self.label_12.setText(_translate("MainWindow", "#"))
        self.spinBox_Range_Steps.setToolTip(_translate("MainWindow", "Number of datasets to select in range."))
        self.toolButton_All_Wavelengths.setToolTip(_translate("MainWindow", "Select all."))
        self.toolButton_All_Wavelengths.setText(_translate("MainWindow", "All"))
        self.toolButton_None_Wavelengths.setToolTip(_translate("MainWindow", "Deselect all."))
        self.toolButton_None_Wavelengths.setText(_translate("MainWindow", "None"))
        self.toolButton_Add_This_File.setToolTip(_translate("MainWindow", "Add selected to plot."))
        self.toolButton_Add_This_File.setText(_translate("MainWindow", "Add"))
        self.toolButton_Add_All_Files.setToolTip(_translate("MainWindow", "For selected wavelenths/timepoints, add data from all open files to plot."))
        self.toolButton_Add_All_Files.setText(_translate("MainWindow", "+ From All Files"))
        self.toolButton_SVD.setToolTip(_translate("MainWindow", "Perform SVD on selected data, and send first n eigenvectors to plot."))
        self.toolButton_SVD.setText(_translate("MainWindow", "SVD"))
        self.spinBox_SVD.setToolTip(_translate("MainWindow", "Set number of SVD eigenvalues to add."))
        self.spinBox_SVD.setSuffix(_translate("MainWindow", " eig"))
        self.checkBox_eigvalue.setToolTip(_translate("MainWindow", "SVD for Matrix = U * Eig * V will return:\n"
" U and V if unchecked;\n"
" U * Eig and Eig * V if checked."))
        self.checkBox_eigvalue.setText(_translate("MainWindow", "Weighted"))
        self.tabWidget_Data.setTabText(self.tabWidget_Data.indexOf(self.tab_Raw_Data), _translate("MainWindow", "Raw Data"))
        self.label_7.setText(_translate("MainWindow", "Plot"))
        self.label_dpiNumber.setText(_translate("MainWindow", "300"))
        self.label_dpi.setText(_translate("MainWindow", "dpi"))
        self.horizontalSlider_DPI.setToolTip(_translate("MainWindow", "Resolution of output image file."))
        self.pushButton_Save_Figure.setToolTip(_translate("MainWindow", "Render current figure into a high-res image file."))
        self.pushButton_Save_Figure.setText(_translate("MainWindow", "Export Figure ..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Time_Traces), _translate("MainWindow", "Time Traces"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Spectra), _translate("MainWindow", "Spectra"))
        self.toolButton_All_Traces.setToolTip(_translate("MainWindow", "Select all traces."))
        self.toolButton_All_Traces.setText(_translate("MainWindow", "All"))
        self.toolButton_None_Traces.setToolTip(_translate("MainWindow", "Deselect all traces."))
        self.toolButton_None_Traces.setText(_translate("MainWindow", "None"))
        self.toolButton_Remove_Selected_Traces.setToolTip(_translate("MainWindow", "Remove selected data from table above."))
        self.toolButton_Remove_Selected_Traces.setText(_translate("MainWindow", "Remove"))
        self.toolButton_Line.setToolTip(_translate("MainWindow", "Toggle selected to line plot."))
        self.toolButton_Line.setText(_translate("MainWindow", "Line"))
        self.toolButton_Scatter.setToolTip(_translate("MainWindow", "Toggle selected to scatter plot."))
        self.toolButton_Scatter.setText(_translate("MainWindow", "Scatter"))
        self.toolButton_Hide.setToolTip(_translate("MainWindow", "Hide plotting for selected."))
        self.toolButton_Hide.setText(_translate("MainWindow", "Hide"))
        self.pushButton_Export_Traces.setToolTip(_translate("MainWindow", "Export selected dataset(s) in the table as KinTek format text file."))
        self.pushButton_Export_Traces.setText(_translate("MainWindow", "Save to txt ..."))
        self.toolButton_Add_By.setToolTip(_translate("MainWindow", "Add selected dataset(s) by a scalar number."))
        self.toolButton_Add_By.setText(_translate("MainWindow", "+"))
        self.toolButton_Mul_By.setToolTip(_translate("MainWindow", "Multiply selected dataset(s) by a number."))
        self.toolButton_Mul_By.setText(_translate("MainWindow", "×"))
        self.label_6.setText(_translate("MainWindow", "By"))
        self.toolButton_Internal_Ref.setToolTip(_translate("MainWindow", "Substract each selected dataset by a internal reference point."))
        self.toolButton_Internal_Ref.setText(_translate("MainWindow", "Internal Ref."))
        self.label_8.setText(_translate("MainWindow", "At"))
        self.doubleSpinBox_Internal_Ref.setToolTip(_translate("MainWindow", "The time/wavelength at which the internal reference is taken."))
        self.doubleSpinBox_Internal_Ref.setSuffix(_translate("MainWindow", " nm"))
        self.toolButton_Ref_To.setToolTip(_translate("MainWindow", "Subtract selected dataset(s) by a reference dataset."))
        self.toolButton_Ref_To.setText(_translate("MainWindow", "Calc. Difference "))
        self.label_9.setText(_translate("MainWindow", "From"))
        self.comboBox_Ref_To.setToolTip(_translate("MainWindow", "Select the reference dataset."))
        self.label_5.setText(_translate("MainWindow", ">>> plt."))
        self.pushButton_Exec.setToolTip(_translate("MainWindow", "Run python command. \n"
" Warning: May screw up stuff."))
        self.pushButton_Exec.setText(_translate("MainWindow", "--> exec()"))
        self.toolButton_Reset.setToolTip(_translate("MainWindow", "Clear all datasets."))
        self.toolButton_Reset.setText(_translate("MainWindow", "Reset"))
        self.pushButton_About.setText(_translate("MainWindow", "About ..."))
        self.label_xRange.setText(_translate("MainWindow", "x-Range"))
        self.checkBox_LogX.setText(_translate("MainWindow", "Log x-Axis"))
        self.label_yRange.setText(_translate("MainWindow", "y-Range"))
        self.checkBox_LogY.setText(_translate("MainWindow", "Log y-Axis"))
        self.toolButton_Apply_Range.setText(_translate("MainWindow", "Apply"))
        self.toolButton_Auto_Range.setText(_translate("MainWindow", "Auto"))
        self.checkBox_Grid.setText(_translate("MainWindow", "Grid"))
        self.checkBox_Legend.setText(_translate("MainWindow", "Legend"))
        self.label_3.setText(_translate("MainWindow", "Font Size"))
        self.spinBox_Font_Size.setToolTip(_translate("MainWindow", "Change plot font size."))
        self.label_4.setText(_translate("MainWindow", "Linewidth"))
        self.doubleSpinBox_Line_Width.setToolTip(_translate("MainWindow", "Change plot line and marker sizes."))
        self.label_2.setText(_translate("MainWindow", "Dot Size"))
        self.label.setText(_translate("MainWindow", "Density"))

